### PR TITLE
Enhance JWT middleware error handling and token parsing

### LINKED ISSUE #317: refactor: Improve JWT authentication
## Description

Improve JWT authentication middleware for enhanced error handling and token extraction. Ensure the middleware checks for the presence of an authorization header and verifies the token format to prevent potential security issues.

## Steps to Reproduce

1. Send a request without an authorization header.
2. Send a request with a malformed "Bearer" token format.
3. Observe the middleware's response.

## Expected Behavior

The middleware should respond with clear error messages if:
- The authorization header is missing.
- The token is improperly formatted.

### PR DESCRIPTION
**Pull request by Viole07**
## Description

Improves JWT authentication middleware for better error handling and token extraction. Adds validation for authorization headers and token format to enhance security and debugging.

- closes #317

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Tests update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)

N/A

### CODE REVIEW

**Comment by yashmandi** [comment]
mention issue number

**Comment by Viole07** [comment]
@yashmandi

**Comment by yashmandi** [comment]
only work if the issue is assigned to you. 
closing this one.

**Comment by Viole07** [comment]
@yashmandi Should I create one again if you would like these changes or were the changes not required..

**Pull request closed without merging**
