### PR TITLE
update delete functionality

### LINKED ISSUE #116: Delete My Account Option Not Working
Assign me this I will look into it @yashmandi

### PR DESCRIPTION
**Pull request by VivekShahare04**
## Description

- Fixes #116

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)
Screenshot (93)
I had made the changes in delete functionality to make it properly work.
@theashikagupta  @yashmandi

### CODE REVIEW

**Comment by theashikagupta** [comment]
Add screen recording @VivekShahare04

**Comment by yashmandi** [comment]
@VivekShahare04 any updates?

**Comment by VivekShahare04** [comment]
@yashmandi  I already changed the functionality and already made a pull request please check it .
actually my local server is not working due to some system issue so, i am attaching updated code recording please look into it.


https://github.com/user-attachments/assets/09356eb5-58d0-4e2f-8d67-b13f95415f3f

@theashikagupta added screen recording of changed code.

**Comment by yashmandi** [comment]
contritbutor inactive, hence closing

**Pull request closed without merging**
