### PR TITLE
Feat: ContactUs Page

### LINKED ISSUE #181: Add contact us page
# Issue Template

## Description

Create a contact us section for homepage and attach with the contact us button on navbar.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to homepage
2. Click on contact us button in navbar
3. See blank page.

## Expected Behavior

When you click on contact us , contact us page should be there.## Screenshots

If applicable, add screenshots to help explain the issue.

## Additional Context

Add this email : yashmandi18@gmail.com

### PR DESCRIPTION
**Pull request by harshbhar0629**
## Description
This is a contact us form and also have side modal.

- Fixes #181 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)

This is index.js inside footer folder it have two components 1.ContactDetail 2. ContactForm

indexFooter

It is a data of contact us detail.

contactDetail

Basic implementation of contact us detail.

contactDetails

Contact us form start inside it main ContactUs form component.

contactUsPre

Contact Form in contact form i used useForm() which can easily manage the state and error as well and it have more feature like like formState after submission formstate is true then it submit successfully otherwise error.

contactForm

UI portion of Contact us form

contactFormUI

@theashikagupta Please review my code and merge it with labels:)

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@theashikagupta  Please assign level-3 because it takes alot of time:)

**Comment by theashikagupta** [comment]
Add screen recording of page

**Comment by harshbhar0629** [comment]
Ok i will

**Comment by harshbhar0629** [comment]
@theashikagupta  Please see video of contactUs page.

UI:

https://github.com/user-attachments/assets/064f2b22-b0da-4a9d-bddb-7943abe9b0a9

**Comment by harshbhar0629** [comment]
???

**Comment by harshbhar0629** [comment]
@yashmandi i created first PR but @theashikagupta  wants video of UI and after i uploaded i video in between someone is make PR and that PR merge it why my you don't wait for my video??

**Comment by harshbhar0629** [comment]
@yashmandi I created a interactive contactUs Page

**Comment by theashikagupta** [comment]
@harshbhar0629 because the issue is not assigned to you

**Comment by harshbhar0629** [comment]
See @theashikagupta 

assigned

**Pull request closed without merging**
