### PR TITLE
added the photos and videos option in notes section

### LINKED ISSUE #125: feature  we can add one image option in the note section
We can add one Image option so that user can save some images also this will help to maintain the interactivity

we can just add one input of image type so that user can only add the image ,  not any other file.
and then we have to store it to db as well so that next time when user visit and recheck they can find it there.

image

### PR DESCRIPTION
**Pull request by Aditya-edith**
fixed the video and image part now the user can add the image and video more  styling can be done later as there is issues in backend please check it .

- Fixes #125  )

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update
- [x] Tests update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)

Add screenshots to help explain the changes (if necessary).

### CODE REVIEW

**Comment by theashikagupta** [comment]
Add screen recording @Aditya-edith

**Comment by Aditya-edith** [comment]
screen recording of UI ? @theashikagupta

**Comment by Aditya-edith** [comment]
https://github.com/user-attachments/assets/11e8bc8b-993b-4d7b-a956-374e173ea557

**Comment by yashmandi** [comment]
looks good, just update the color of 'save note' button, match it with the theme color instead of blue. then we can merge it.

**Comment by Aditya-edith** [comment]
https://github.com/user-attachments/assets/1b9cf823-31d9-4d44-a59c-ee491814e160

@yashmandi

**Comment by Aditya-edith** [comment]
hey have u checked that ??
@yashmandi

**Pull request merged**
