### PR TITLE
Enhanced Footer and made it responsive #96

### LINKED ISSUE #96: Improve footer
# Issue Template

## Description

The footer is too huge and looks very basic and also lacks social icons (like instagram, X, github, etc)

## Screenshots

image

I want to fix this issue. @yashmandi , plz assign ,me this task under gssoc-extd label

### PR DESCRIPTION
**Pull request by devarsheecodess**
## Description

1. Enhanced the Footer UI by adding social icons and making it thin/short
2. Made it responsive

- Fixes #96

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)

scribbie#2
scribbie#1

### CODE REVIEW

**Comment by yashmandi** [comment]
good work @devarsheecodess , can you please add the scroll-to-top button as well.
try to add it at the bottom right corner, then we are good to go ;)

**Comment by devarsheecodess** [comment]
> good work @devarsheecodess , can you please add the scroll-to-top button as well. try to add it at the bottom right corner. and also on desktop screen, keep the logo at center and not at left side.
> 
> update the changes then we are good to go ;)

Sure, give me some time

**Comment by devarsheecodess** [comment]
https://github.com/user-attachments/assets/f2d24529-f3c9-4e50-91c6-419120fa9ee8

@yashmandi plz add gssoc-ext, hacktoberfest-accepted and level2 label here too as some of my PRs were not counted for GSSoC

**Comment by yashmandi** [comment]
good work @devarsheecodess !
kindly resolve the merge conflicts

**Comment by devarsheecodess** [comment]
Hi, i have resolved the conflicts and have added a scroll on top button. Plz add the labels on pull request too as it was told to us today by the program manager
image

**Pull request merged**
