### PR TITLE
FIX : dark mode #117

### LINKED ISSUE #117: Dark Mode Not Applying Styles Correctly
# Issue Template

# Issue Template

## Description

Dark mode is not applying the expected styles on the note-taking website. This issue occurs in the latest version of the application when viewed in a modern browser.

## Steps to Reproduce

1. Go to the  website.
2. Settings
3. Toggle the dark mode switch.
4. Observe that the styles for dark mode are not applied correctly.

## Expected Behavior

The dark mode should change the theme colors appropriately.

## Actual Behavior

The dark mode toggle does not apply the correct styles, and the site remains in light mode.

## Screenshots

Dark mode not working
)

## Additional Context

This issue was observed in the latest version of the application on Chrome. Console logs indicate that the dark mode styles are not being applied.

### PR DESCRIPTION
**Pull request by RaiDevX8**
## Description

Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.

- Fixes #117 

## Type of change
This update introduces a dark mode feature that allows users to toggle between light and dark themes across the application. The user's theme preference is saved in local storage, ensuring that the selected theme persists across sessions. This addresses the need for better user experience and accessibility in the app

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)

Screenshot 2024-10-18 130559
Screenshot 2024-10-18 130618
Screenshot 2024-10-18 130640
Screenshot 2024-10-18 130706

Note :@yashmandi i have made dark mode feature not applied styles if you want i will create new issue for design issue

### CODE REVIEW

**Comment by yashmandi** [comment]
> ## Description
> Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.
> 
> * Fixes [Dark Mode Not Applying Styles Correctly #117](https://github.com/Scribbie-Notes/notes-app/issues/117)
> 
> ## Type of change
> This update introduces a dark mode feature that allows users to toggle between light and dark themes across the application. The user's theme preference is saved in local storage, ensuring that the selected theme persists across sessions. This addresses the need for better user experience and accessibility in the app
> 
> * [x]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> 
> ## Checklist
> * [x]  My code follows the style guidelines of this project
> * [x]  I have performed a self-review of my own code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  My changes generate no new warnings
> * [x]  New and existing unit tests pass locally with my changes
> * [x]  I have maintained a clean commit history by using the necessary Git commands
> * [x]  I have checked that my code does not cause any merge conflicts
> 
> ## Screenshots (if applicable)
> Screenshot 2024-10-18 130559 Screenshot 2024-10-18 130618 Screenshot 2024-10-18 130640 Screenshot 2024-10-18 130706
> 
> Note :@yashmandi i have made dark mode feature not applied styles if you want i will create new issue for design issue

create new issue

**Comment by RaiDevX8** [comment]
@yashmandi please assign and close this issue i will create new

**Comment by RaiDevX8** [comment]
@theashikagupta i impliemented the dark theme functionality why you closed ?

**Comment by RaiDevX8** [comment]
@theashikagupta i impliemented the dark theme functionality why you closed ?

**Pull request closed without merging**
