### PR TITLE
Fix event listener on button for full clickable area

### PR DESCRIPTION
**Pull request by Aryan-dev-enth**
This PR fixes the issue where only the icon within the button had the event listener. Now, the entire button is clickable, enhancing the user experience.

### CODE REVIEW

**Comment by Aryan-dev-enth** [comment]
[Scribbie - Google Chrome 2024-10-02 22-11-42.zip](https://github.com/user-attachments/files/17233044/Scribbie.-.Google.Chrome.2024-10-02.22-11-42.zip)

**Comment by theashikagupta** [comment]
Mention issue number.

**Comment by Aryan-dev-enth** [comment]
Add tag button not working properly #23

**Comment by theashikagupta** [comment]
Good Job! @Aryan-dev-enth

**Pull request merged**
