### PR TITLE
added navbar

### LINKED ISSUE #152: adding navbar
# Issue Template

## Description
Objective: I propose enhancing the navbar like this

https://github.com/user-attachments/assets/b77b0b3c-563d-4515-b404-261c52a043de

Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24 , hacktoberfest.

Looking forward to your feedback

### PR DESCRIPTION
**Pull request by priyashuu**
## Description

Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.

- Fixes #152 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)
image

Add screenshots to help explain the changes (if necessary).

### CODE REVIEW

**Comment by priyashuu** [comment]
https://github.com/user-attachments/assets/37c4ec86-a276-483c-9892-5e7e7e7b7e

**Comment by priyashuu** [comment]
which one ?

**Comment by theashikagupta** [comment]
Second one looks better

**Comment by priyashuu** [comment]
hey @theashikagupta ,  It was originally assigned to Level 3 when I created it, as I felt it deserved that level of attention and complexity. I noticed it was m Level 2, and I’m feeling a bit concerned about this change.

**Comment by priyashuu** [comment]
https://github.com/user-attachments/assets/0a3cf5e3-a19d-4940-a11f-7b2b4bbb24c1

**Comment by theashikagupta** [comment]
@priyashuu These changes are the part of frontend and it doesn't have level3 complexity .Also we give level3 for those Prs in which backend is involved.

**Review by theashikagupta — APPROVED** [review]
Excellent job ! @priyashuu

**Comment by priyashuu** [comment]
I’ve incorporated libraries like GSAP and Framer Motion to enhance the animations. If there are any specific elements you’d like to see in the navbar or if there’s something that doesn’t meet your expectations, I’d be happy to make the necessary changes. "Please add a Level 3 feature to the Navbar as it was assigned in the issue creation. . What else do you want in the backend,please dont do this

**Comment by priyashuu** [comment]
@theashikagupta , @yashmandi

**Pull request merged**
