### PR TITLE
profile photo update issue 

### LINKED ISSUE #108: the user photo is not getting updated
# Issue Template

## Description

when the user try to change the profile photo it do not get updated

## Steps to Reproduce
i will review the code and resolve the error in the backend or on the frontend

@yashmandi please assign this issue to me

### PR DESCRIPTION
**Pull request by AyushSharma72**
## Description

the profile photo of the user was not getting updated i fixed the issue by simply correcting the backend url in the axios function

Screenshot 2024-10-17 165911

now is is uploded
Screenshot (276)

also i have noticed you did not give proper url of the backend api due to which the functionality are not working such as login sign up 

- Fixes #108
f necessary).

### CODE REVIEW

**Comment by theashikagupta** [comment]
Attach screen recording of implementation @AyushSharma72

**Comment by AyushSharma72** [comment]
> Attach screen recording of implementation @AyushSharma72

https://github.com/user-attachments/assets/d58c25c1-1767-433a-ba5b-2e83feee0fb4

**Comment by yashmandi** [comment]
upload any random photo from your local device and then record it

**Comment by AyushSharma72** [comment]
> upload any random photo from your local device and then record it

I did the same in the video the browser do not record the computer screen which selecting photo 
You can see the toast notification in the video after I upload the photo  @yashmandi

**Comment by yashmandi** [comment]
resolve merge conflicts. will merge the pr

**Comment by AyushSharma72** [comment]
> resolve merge conflicts. will merge the pr

check now @yashmandi

**Pull request merged**
