### PR TITLE
Added 3 buttons to NavBar

### PR DESCRIPTION
**Pull request by bhargava-raju**
## Description

Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.

- Fixes #(issue number)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)

Add screenshots to help explain the changes (if necessary).

### CODE REVIEW

**Comment by bhargava-raju** [comment]
@praneethasingh, @Prakhar29Sharma, kindly review the PR

**Comment by bhargava-raju** [comment]
https://github.com/Scribbie-Notes/notes-app/issues/18 is fixed

**Comment by yashmandi** [comment]
kindly add the screenshots @bhargava-raju

**Comment by bhargava-raju** [comment]
image

**Comment by bhargava-raju** [comment]
> kindly add the screenshots @bhargava-raju

image

**Comment by theashikagupta** [comment]
Kindly place all the three buttons on right side .

**Pull request closed without merging**
