### PR TITLE
Integrated TinyMCE to notes app

### PR DESCRIPTION
**Pull request by KGupta2601**
TinyMCE is a rich-text editor that allows users to create formatted content within a user-friendly interface. I have integrated it in notes app.
Solves issue #176 

@theashikagupta @yashmandi 
kindly review my PR and provide the labels of gssoc extended,hactoberfest accepted and level 2.
Also let me know if there are any changes to be made.

### CODE REVIEW

**Comment by KGupta2601** [comment]
@yashmandi @theashikagupta 
kindly review my PR and provide the labels of gssoc extended,hactoberfest accepted and level 2.
Also let me know if there are any changes to be made.

**Comment by theashikagupta** [comment]
Add screen recording

**Comment by theashikagupta** [comment]
Add screen recording

**Comment by KGupta2601** [comment]
The pull request was closed due to the synchronization of fork I had to discard the changes I did 
So I am reopening it again .

**Comment by KGupta2601** [comment]
> @KGupta2601 Attach screen recording of the implementation.

@theashikagupta yes I am working on it 
Actually I am encountering some issues in setting up the backend in my laptop so I am trying to resolve them

**Comment by theashikagupta** [comment]
No issues Take your time @KGupta2601

**Comment by KGupta2601** [comment]
image
@theashikagupta I am unable to sign in

**Comment by KGupta2601** [comment]
[TinyMCE.webm](https://github.com/user-attachments/assets/82e88791-daa1-4174-a224-5217da56474f)
This is the screen recording
@theashikagupta kindly check the attached screen recording of my implementation

**Comment by KGupta2601** [comment]
@yashmandi Kindly check the recording I have attached
If there are any further changes to be done, please let me know.

**Pull request merged**
