### PR TITLE
Fix the error showing on signup and login

### LINKED ISSUE #49: BUG: Fix the error showing on signup and login .
# Issue Template

## Description

Fix the error showing on signup and login .

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to 'signup' or login
2. Fill details 
3. Submit

## Expected Behavior

After fill up the details correctly it should signup or login 

## Actual Behavior

Showing error after fillup the details .

## Screenshots

Screenshot 2024-10-02 215614

### PR DESCRIPTION
**Pull request by Saurabhchaudhary9799**
## Description
This PR addresses issue by fixing error during signup and login .

- Fixes #49 

## Type of change
-bug fix

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)
**login recording**
[Screencast from 2024-10-25 22-07-26.webm](https://github.com/user-attachments/assets/e55d2842-8c61-4885-8ee2-eb2f6801b46c)

**signup recording **
[Screencast from 2024-10-25 22-06-12.webm](https://github.com/user-attachments/assets/5e753374-77b4-40ba-905b-944f751df224)

### CODE REVIEW

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta , Please check this PR.

**Comment by Saurabhchaudhary9799** [comment]
@theashikagupta , please add level3 label on this PR.

**Comment by theashikagupta** [comment]
Not worked yet
Issue is something else regarding database

**Comment by Saurabhchaudhary9799** [comment]
> Not worked yet Issue is something else regarding database

This is woking in my local machine properly.

**Comment by Saurabhchaudhary9799** [comment]
> > Not worked yet Issue is something else regarding database
> 
> This is woking in my local machine properly.

what type of error is coming now .

**Comment by theashikagupta** [comment]
Quotes will come around mongodb uri but issue it starting mongodb . It is showing error when I run mongod

**Comment by Saurabhchaudhary9799** [comment]
BREVO_USER=//your_brevo_user
BREVO_PASSWORD=//your brevo_password
BREVO_HOST="smtp-relay.brevo.com"
BREVO_PORT=587



MONGO_URI=mongodb://localhost:27017/notes-app
PORT=5000
ACCESS_TOKEN_SECRET=//your_token
GOOGLE_API_TOKEN=""


Replace your .env file with this and check it . and send me screenshots also.

**Pull request merged**
