### PR TITLE
add dark mode

### LINKED ISSUE #153: add dark mode toggle button
# Issue: Add Dark Mode Toggle Button

## Description

A dark mode toggle button is needed for the application to allow users to switch between light and dark modes. This feature should be available on all pages and remember the user's preference. It should also smoothly integrate with the existing design and components.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to any page of the website.
2. Look for a dark mode toggle button.
3. Click on it to attempt switching modes.
4. Observe if there is a toggle functionality or if the feature is missing.

## Expected Behavior

A visible dark mode toggle button should allow users to seamlessly switch between light and dark themes. The theme preference should be stored in local storage or a similar method to persist across sessions.

## Actual Behavior

Currently, there is no option to toggle between light and dark modes.

## Additional Context

The dark mode should be implemented with smooth transitions for colors and themes. Consider accessibility aspects such as contrast ratios when designing the dark theme.

### PR DESCRIPTION
**Pull request by priyashuu**
## Description

Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.

- Fixes #153

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)
image

Add screenshots to help explain the changes (if necessary).

### CODE REVIEW

**Review by theashikagupta — CHANGES_REQUESTED** [review]
Use single button only . There is no need to add two buttons.

**Comment by theashikagupta** [comment]
Please add screen recording

**Comment by priyashuu** [comment]
https://github.com/user-attachments/assets/44c0a8ea-d67d-4e13-bb67-fa1444e46a5f

**Comment by theashikagupta** [comment]
Darkmode is not applied in navbar . Kindly correct them.

**Comment by priyashuu** [comment]
image

**Comment by priyashuu** [comment]
now ? @theashikagupta

**Comment by priyashuu** [comment]
https://github.com/user-attachments/assets/4f5cceb2-fa6b-4b56-ae70-b6ad243bafe6

**Comment by yashmandi** [comment]
image
the dark mode color is not matching with the navbar bg, fix it

**Comment by priyashuu** [comment]
image

**Comment by priyashuu** [comment]
@yashmandi check this one

**Pull request merged**
