### PR TITLE
update_layout: Updated the layout of the testimonial section

### LINKED ISSUE #100: feature: Adjust Design for Customer Review (Testimonial) Page
## Description
We need to enhance the design of the Customer Review (Testimonial) page to improve user experience and better align with the overall website aesthetic. While the current layout isn't outdated, it lacks strong visual appeal, and the testimonials could be presented more effectively to highlight customer feedback.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to Home page.
2. Scroll down to to the review section (testimonial section)

## Propose Change (Screenshot)
Screenshot 2024-10-05 at 1 52 58 AM

I have more of these pictures to add (here for showcase): 
09fae65f-6cc6-46c1-9ecb-5080812b3d11
11553de6-0f08-4e9a-b7a4-bf46397a4c0d
ab68ce2c-c526-42c2-ba20-3b448e80827f

### PR DESCRIPTION
**Pull request by userAdityaa**
## Description

I updated the layout of the testimonial section to improve its visual appearance and overall user experience. Additionally, I incorporated images to create a more engaging and dynamic design. The grid layout issues were also resolved to ensure proper alignment and responsiveness across different screen sizes.

- Fixes #100 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Tests update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)
Screenshot 2024-10-05 at 1 10 38 PM

### CODE REVIEW

**Comment by userAdityaa** [comment]
@yashmandi, Ready for review!

**Comment by userAdityaa** [comment]
Hey @yashmandi, There were no label in this PR. So, it was not contributed towards gssoc. Kindly add the gssoc label with the level.

**Comment by Vaishh18** [comment]
Hey @userAdityaa could we connect? I am facing a small problem ,needed help!

**Comment by yashmandi** [comment]
hi @userAdityaa , i am also looking to change the hero section image, which should be similar to what u added in testimonial section. please let me know if you can replace the below image with something similar way u added previously.
image

**Comment by userAdityaa** [comment]
Ok marking an issue for it. @yashmandi

**Pull request merged**
