### PR TITLE
preloader added

### LINKED ISSUE #95: feat : adding preloader animation
## Description
please assign this to me
 
adding animation using framer motion to landing page which improve UX .

Screenshot (135)

### PR DESCRIPTION
**Pull request by itznayan**
## Description

Preloader added

- Fixes #95 

## Type of change

Please delete options that are not relevant.

- [X ] New feature (non-breaking change which adds functionality)

## Checklist

- [X ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes
- [X] I have maintained a clean commit history by using the necessary Git commands
- [X] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)

Add screenshots to help explain the changes (if necessary).

### CODE REVIEW

**Comment by itznayan** [comment]
Here's the preview of Preloader. 
@yashmandi @theashikagupta 

https://github.com/user-attachments/assets/4145aeba-b0ee-428b-9e64-f42faf2ed4b2

**Comment by itznayan** [comment]
@yashmandi  @theashikagupta 
https://github.com/user-attachments/assets/a674706a-36c6-4227-b548-a31c4925eeb0

**Comment by itznayan** [comment]
Kindly check PR @yashmandi @theashikagupta 


https://github.com/user-attachments/assets/7c429f8a-6c33-4104-ba4b-788af3b8c903

**Comment by yashmandi** [comment]
good work !

**Pull request merged**
