### PR TITLE
fix 404 Not Found Page on Refresh After Deployment 

### LINKED ISSUE #36: bug : 404 Page Not Found Error After Deployment
### Description:
 When a user refreshes the page after navigating to a specific route, they are redirected to a 404 Not Found page. This issue occurs regardless of whether the user has logged in, signed up, or simply navigated to a page that should be accessible. The lack of proper routing or handling for these page refreshes is causing confusion and hindering user experience.

### Expected Behavior: 
Upon refreshing the page, users should remain on the current page they were viewing or be directed to a default landing page, rather than encountering a 404 Not Found error. Proper routing and state management should ensure that valid pages are accessible even after a refresh.

### Steps to Reproduce:
1. Navigate to any route within the application (e.g., login, signup, dashboard).
2. Refresh the page using the browser's refresh button.
3. Observe that the user is redirected to a 404 Not Found page.

### Proposed Solution:
- Implement proper routing logic to handle page refreshes gracefully.
- Ensure that valid routes are retained in the application's state, so users are directed to the correct pages after a refresh.

### PR DESCRIPTION
**Pull request by Saurabhchaudhary9799**
### What does this PR do
This PR addresses issue #36  by fixing the redirecting to 404 not found page on refreshing the page regardless of whether the user has logged in, signed up, or simply navigated to a page that should be accessible

### What Changed
-  update route configuration in vercel.json

### How to Test

1. Navigate to any route within the application (e.g., login, signup, dashboard).
2. Refresh the page using the browser's refresh button.
3. Observe the changes.

### Related Issues
Fixes #36

### CODE REVIEW

**Comment by theashikagupta** [comment]
Please don't create PR without assigning to you

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta , from now  i will make sure to follow the required format in future PRs.
For this PR, I've addressed the necessary changes, and I believe it meets the project's requirements. If you could take a look and consider merging it, I would greatly appreciate it.

**Comment by Saurabhchaudhary9799** [comment]
> @Saurabhchaudhary9799 kindly share the screenshots of changes, then we'll merge it
hey @yashmandi  , are you asking for code changes screenshot or visual changes screenshot after changing the code.

**Comment by yashmandi** [comment]
> > @Saurabhchaudhary9799 kindly share the screenshots of changes, then we'll merge it
> > hey @yashmandi  , are you asking for code changes screenshot or visual changes screenshot after changing the code.

visual changes, what changes have you done in frontend

**Comment by Saurabhchaudhary9799** [comment]
hey @yashmandi  , the issue was solved by this PR related to after deployment , you can see the  changes after deployement only.

**Pull request closed without merging**
