### PR TITLE
Implement basic text formatting options in note editor

### PR DESCRIPTION
**Pull request by ManasaNagaram**
## Description

Add text formatting options: bold, italic, underline, headings, and lists in note editor

- Fixes (#160)

## Type of change

- [ ] New feature :  implement a basic text editor within the application that will allow users to create and edit notes with basic formatting options. This is a fundamental feature for the notes-taking app and should be simple, intuitive, and responsive.

## Checklist

- [yes ] My code follows the style guidelines of this project
- [yes ] I have performed a self-review of my own code
- [ yes] I have commented my code, particularly in hard-to-understand areas
- [yes ] My changes generate no new warnings
- [ yes] New and existing unit tests pass locally with my changes
- [yes ] I have maintained a clean commit history by using the necessary Git commands
- [yes ] I have checked that my code does not cause any merge conflicts

### CODE REVIEW

**Comment by yashmandi** [comment]
add screen recording of the implementation

**Comment by ManasaNagaram** [comment]
> add screen recording of the implementation
https://github.com/user-attachments/assets/9f88ce1e-2417-4c86-99dd-718d72482ddf

**Comment by theashikagupta** [comment]
Resolve merge conflicts. @ManasaNagaram

**Comment by ManasaNagaram** [comment]
> Resolve merge conflicts. @ManasaNagaram

done

**Comment by yashmandi** [comment]
good work @ManasaNagaram

**Pull request merged**
